### ISSUE TITLE
Feedback for improvement 

### ISSUE THREAD

**Issue by nsherani** [u-blox/XPLR-HPG-software#13]
I tried flashing the board with both the official software and the Mazgch software. Here are some points I want to mention:

Mazgch software is more user-friendly. The latest version of [Mazgch](https://github.com/mazgch/hpg) is stable and has a good captive portal, making it easy to switch between services like MQTT and NTRIP without re-flashing the board. You just change the setting in the portal.

On the other hand, the [XPLR-HPG software](https://github.com/u-blox/XPLR-HPG-software) has a captive portal only for MQTT. For NTRIP, you need to re-flash the board. If you want to use LTE, you have to re-flash the board every time you switch services.

This is my user experience and feedback for improvement. Thanks!

**Comment by aangeletos** [comment]
> I tried flashing the board with both the official software and the Mazgch software. Here are some points I want to mention:
> 
> Mazgch software is more user-friendly. The latest version of [Mazgch](https://github.com/mazgch/hpg) is stable and has a good captive portal, making it easy to switch between services like MQTT and NTRIP without re-flashing the board. You just change the setting in the portal.
> 
> On the other hand, the [XPLR-HPG software](https://github.com/u-blox/XPLR-HPG-software) has a captive portal only for MQTT. For NTRIP, you need to re-flash the board. If you want to use LTE, you have to re-flash the board every time you switch services.
> 
> This is my user experience and feedback for improvement. Thanks!

Thank you for your feedback, we will consider captive portal updates for next releases.
Best regards,
Alex
