### ISSUE TITLE
Thingstream MQTT Cellular examples

### ISSUE THREAD

**Issue by aangeletos** [u-blox/XPLR-HPG-software#2]
After a recent update in Thingstream MQTT service regarding the correction data topic, the examples provided that make use of the cellular module do not function as expected.<br>
As a result the GNSS module is receiving only part of the correction data thus high precession location cannot be achieved.<br>
The issue has been identified and will be fixed with the next release which is planned for mid August.

**Comment by fng97** [comment]
Hiya, I've been observing this issue but only just noticed this ticket. I assume this is the reason I've noticed that in places where the captive portal example gets an RTK float immediately, the cellular module only ever gets a 3D fix. Looking at the device and ThingStream logs, the device is definitely connected and receiving corrections on `/pp/ip/eu`. Any movement on this? If not, could you point me in the right direction for trying to fix this? In case it's relevant, I've got a green C214.

**Comment by aangeletos** [comment]
> 

Hello @fng97, <br>
the fix to the issue is planned to be included in the next release which will be available mid August.<br>
If you are in a hurry and want to try/evaluate the cellular examples I can share the updated file with you that you will have to replace it, manually, in your sources.<br>
To do so, please replace `xplr_mqtt_client.c` which is located [here](https://github.com/u-blox/XPLR-HPG-software/tree/main/XPLR-HPG-SW/components/hpglib/src/mqttClient_service) with the one I m attaching to this post
[xplr_mqtt_client-tsUpdateFix.zip](https://github.com/u-blox/XPLR-HPG-software/files/12171341/xplr_mqtt_client-tsUpdateFix.zip)

Please let me know if it worked for you.

Best,
Alex

**Comment by fng97** [comment]
> Hello @fng97, the fix to the issue is planned to be included in the next release which will be available mid August. If you are in a hurry and want to try/evaluate the cellular examples I can share the updated file with you that you will have to replace it, manually, in your sources. To do so, please replace `xplr_mqtt_client.c` which is located [here](https://github.com/u-blox/XPLR-HPG-software/tree/main/XPLR-HPG-SW/components/hpglib/src/mqttClient_service) with the one I m attaching to this post [xplr_mqtt_client-tsUpdateFix.zip](https://github.com/u-blox/XPLR-HPG-software/files/12171341/xplr_mqtt_client-tsUpdateFix.zip)
> 
> Please let me know if it worked for you.
> 
> Best, Alex

Hiya @aangeletos, that did the trick. Got a float in seconds and a fix after a couple minutes. Thank you very much for sending that fix over!

**Comment by aangeletos** [comment]
Issue is resolved by latest release [v1.0](https://github.com/u-blox/XPLR-HPG-software/releases/tag/v1.0).
