### ISSUE TITLE
Example project hpg_cell_register not working - LARA module not responding

### ISSUE THREAD

**Issue by ftesta-es** [u-blox/XPLR-HPG-software#3]
Project builds and flashes correctly on the board.

However, the LARA R6 cellular module configuration fails as reported in the screenshot below.
It seems there is no communication back from the LARA module.

![image](https://github.com/u-blox/XPLR-HPG-software/assets/138900920/bf3f83c0-4111-4b12-a252-7f07d64d3ca4)

Looking also on the integration manual of the LARA R6, the power-on of the module should be done by toggling the PWR ON pin (High-Low-High): this operation doesn't seem to be carried out correctly from the console messages (and also sniffing the PWR ON pin with an oscilloscope).

**Comment by dbou-ublox** [comment]
Hi there,

not sure if this would help, but which board do you have and what board settings have you chosen in Kconfig?

**Comment by ftesta-es** [comment]
Hi,
the board I'm using is the XPLR-HPG-2, which is the one selected also on the menuconfig target board option (namely "XPLR HPG2 C214 (NINA-W106").

**Comment by dbou-ublox** [comment]
So the color of the PCB is green (and not black), correct?

**Comment by ftesta-es** [comment]
Apologies, the board is the black one indeed, not green

Inviato da Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: dbou-ublox ***@***.***>
Inviato: Saturday, July 8, 2023 4:51:51 PM
A: u-blox/XPLR-HPG-software ***@***.***>
Cc: Filippo Testa ***@***.***>; Author ***@***.***>
Oggetto: Re: [u-blox/XPLR-HPG-software] Example project hpg_cell_register not working - LARA module not responding (Issue #3)


So the color of the PCB is green (and not black), correct?

**Comment by dbou-ublox** [comment]
No worries. So with the MAZGCH board config everything is ok?

**Comment by ftesta-es** [comment]
I've built the example project for the MAZGCH board and it works, thanks!

**Comment by ftesta-es** [comment]
Now I'm getting some issues while trying to change the RAT list of the module:
 
![image](https://github.com/u-blox/XPLR-HPG-software/assets/138900920/6e2bcfe8-af85-42bc-b9d7-abbb90c056dd)

Which is the cause of this?

**Comment by aangeletos** [comment]
Hello @ftesta-es,

it seems that you are having an issue probably with your SIM card and/or cellular network provider.<br>
We did try your RAT configuration and we cannot replicate the issue you are facing (please see attached image).<br>

<hr>

![LARA R6D registering to GSM network](https://github.com/u-blox/XPLR-HPG-software/assets/5342623/46629d12-a59d-4a4b-bda2-14d0e71c7052)

<hr>

Maybe @RobMeades  can shed some more light into this, other wise you will need to contact ublox's cellular support team. <br>
In the meantime it might be helpful to share some more details regarding you location and SIM - carrier you are using.

**Comment by ftesta-es** [comment]
Hi,

actually it seems that I'm not able to change the RAT with the desired one: indeed, during the configuration process I get the error reported in the previous email. While from your screenshot, it seems that you're effectively changing the RAT options.
Are there specific steps to be carried for having a successful configuration?

I'm using an eminfy sim from Italy; other colleagues used it on other modules without issues (mainly using CAT M1 and back-up on GSM/GPRS). Is the CAT M1 RAT supported from the LARA module?

Do you have any other suggestion or possible hint for something to try?

Thanks!

**Comment by aangeletos** [comment]
Silly question but have you configured your APN correctly and hit `Save` in menuconfig?<br>
Ubxlib takes care most of the registration parts and it incorporates the recommended AT Commands according to the cellular module you are using each time.<br>
One thing you could try is to tinker around with the [hpg cellular register](https://github.com/u-blox/XPLR-HPG-software/tree/main/XPLR-HPG-SW/examples/cellular/01_hpg_cell_register) example and try the available RATs until you find one that would register you to a network. I would suggest to only set one RAT at a time and see which one is working for you.
Please make sure that you are configuring your APN correctly through menuconfig  as well.<br>
Second option would be to try using [m-center](https://www.u-blox.com/en/product/m-center) and see what networks and APNs does the module pick when you try the `Get List` option under the `Network` tab.

**Comment by mazgch** [comment]
LARA modules support LTE Cat 1 and depending on the variant also 3G or 2G/GSM fallback.

Use SARA-R4/R5 if you need LTE Cat M1 or NB1.

You can check our datasheets and manuals for RAT supported.

**Comment by ftesta-es** [comment]
Hi all,
many thanks for your hints. I'm trying all the suggested procedure - without success so far.
Actually I'm using an SMA extension cable for both the LTE antennas.
Is this one suitable or the RP version is required for LTE antennas?
In the meantime I'll check if I am able to install the kit LTE antenna directly onto the board.
Thanks.

**Comment by tcha-ublox** [comment]
C214 has normal SMA connectors. I would suggest that you use the kit LTE antennas directly onto the board in order to rule out issues with the SMA extension cables that you are using.

**Comment by aangeletos** [comment]
Hello @ftesta-es, 

can it be that your cellular module has an old firmware?<br>
can you please verify that LARA module is on firmware version `00.13,A00.01` ?
you can get this info from mCenter by connecting to the `AT and Data` port and clicking the `Get info` button.<br>
![image](https://github.com/u-blox/XPLR-HPG-software/assets/5342623/aa667094-2271-42e0-9ab8-20711e961402)

**Comment by ftesta-es** [comment]
Hi @aangeletos,

I confirm the LARA has the correct firmware:
![image](https://github.com/u-blox/XPLR-HPG-software/assets/138900920/9c8459fe-0e13-47d6-a18c-382a7ded17e0)

Also, it seems to recognize correctly the sim insertion, but however it doesn't get any connection to cellular network.
Furthermore, it appears that no IMEI code is displayed on the m-center, while running the AT+CGSN command the module answers with +CME ERROR: memory failure.
Do we have some issue with the LARA module itself?
Thanks

**Comment by aangeletos** [comment]
Hello again,
it seems that your LARA-R6 module has reached an unrecoverable state and you will need to replace your kit.
Please contact your distributor.

Best,
Alex
