### ISSUE TITLE
Example 03_hpg_wifi_mqtt_correction_certs - not getting RTK correction

### ISSUE THREAD

**Issue by ftesta-es** [u-blox/XPLR-HPG-software#5]
Hi,

I've correctly built and flashed the example project, providing the credentials required as reported in the readme file.
However, even after many minutes, the board doesn't seem to get the RTK (float or fixed): 
![image](https://github.com/u-blox/XPLR-HPG-software/assets/138900920/54d6852c-0df7-496e-bd1d-f03302435e44)

Does the RTK correction service have some area with minor/less coverage?
Am I getting something wrong with project settings or config?

Thanks

**Comment by aangeletos** [comment]
Hello @ftesta-es, 

from the log you posted I can see that correction data are forwarded to ZED module which means that you are properly connected to Thingstream's Point Perfect MQTT broker. A bigger log would help to verify that you are connected to the required topics though. <br>
May I ask what type/model of GNSS antenna are you using?<br>
Is the antenna placed outdoors facing the sky?<br>
Are you using any cable extenders for the GNSS antenna connection?

**Comment by ftesta-es** [comment]
Hi @aangeletos,

thanks for the feedback.
I am using the kit antenna, mounted outdoor and facing upward the sky. Also, the antenna is connected to the board with a 20cm SMA extension cable.

Which kind of log/information do you need in order to verify the proper connection to MQTT topics?
Is the initial part of the terminal output sufficient for this analysis?

Thanks

**Comment by ftesta-es** [comment]
Hi,

please find attached a complete log file from board startup. Hope this will better support our discussion.

[rtk_log.txt](https://github.com/u-blox/XPLR-HPG-software/files/12030648/rtk_log.txt)

Let me know if you need more information and details.
Thanks

**Comment by aangeletos** [comment]
> Hi,
> 
> please find attached a complete log file from board startup. Hope this will better support our discussion.
> 
> [rtk_log.txt](https://github.com/u-blox/XPLR-HPG-software/files/12030648/rtk_log.txt)
> 
> Let me know if you need more information and details. Thanks

Thank you for the log Filippo,

it looks like you have everything set correctly from the software side and that ZED-F9R firmware on your device is the correct one (1.30).<br>
Please allow me a day or two to find an appropriate contact for you from the positioning department as they can definitely provide you with more detailed feedback regarding module's features and functionality.

**Comment by ftesta-es** [comment]
Hi there @aangeletos,

Have you had the chance to better investigate our issue while getting RTK-fixed?
Apparently it is able now to reach RTK-float condition, but not the fixed one.

Is there any specific configuration of the F9 module needed to reach this condition?
For example, reducing the number of max satellites or active constellations?

thanks, best regards

**Comment by dbou-ublox** [comment]
Hello @ftesta-es ,
sorry for the late reply but we had to contact different departments to get some answers for you, although maybe not good enough.
Regarding RTK-Fixed/Float and in general the type of fix that you are getting it may well be related to the time of day and the specific location you are conducting your tests. 
You also need to make sure that your GNSS antenna has a clear sky view. 
There is nothing you can do software wise to improve this, at least to our knowledge.
For more specific answers on this matter you can always contact [u-blox support portal](https://portal.u-blox.com)
