### ISSUE TITLE
XPLR-HPG-2 The black board

### ISSUE THREAD

**Issue by rheyu-blox** [u-blox/XPLR-HPG-software#7]
Hi, 

I have an HPG-2 black board and I have a problem that the cellular module keeps resetting. I read in one of the manuals it is a normal behavior apparently. But, the problem is that I cannot implement the cellular example "Achieving High Precision GNSS via correction data taken from Thingstream, using Cellular.(case 2)". I don't have any issue with the HPG-2 green board executing this example. 

All the best, 
Reza Heydarian.

**Comment by dbou-ublox** [comment]
Hi there,

If you use the black board, you have to change the board config to MAZGCH (different PCB routing). See https://github.com/u-blox/XPLR-HPG-software/issues/3#issuecomment-1628597707

**Comment by dbou-ublox** [comment]
Also, beware that CEL examples may be broken, see https://github.com/u-blox/XPLR-HPG-software/issues/2

**Comment by rheyu-blox** [comment]
After changing the board config to the MAZGCH it worked. Thank you. But is it mentioned somewhere in some of our manuals?

**Comment by dbou-ublox** [comment]
Great.
It should be already mentioned in the READMEs of the different examples, like [this ](https://github.com/u-blox/XPLR-HPG-software/tree/main/XPLR-HPG-SW/examples/shortrange/02_hpg_wifi_http_ztp#kconfigbuild-definitions-macros)one. Maybe it's mentioned in all, could be the case

**Comment by rheyu-blox** [comment]
Even in the link you sent I can't find any  information related changing the board config to MAZGCH. It says that select the board you wish to build your example for. But how can I find out which choice is the right one. In which document can I find this info?

**Comment by dbou-ublox** [comment]
The example README I provided mentions the changes you have to make to the KConfig, in order to run the example (different KConfig settings for different examples typically). Which assumes that the user goes through the README to make an example work (and part of the instructions is to make sure the board used is correct).
Probably this is not enough. Open to suggestions on where to put such information, so other users are helped as well

**Comment by rheyu-blox** [comment]
Maybe only a hint would be sufficient in the building instruction section, under step 6, something like this:


For HPG-2 black boards, set board options to "MAZGCH HPG SOLUTION (NINA-W106)"
For HPG-2 green boards, set board options to "XPLR HPG2 C214 (NINA-W106)"


 would help a lot. This is just a suggestion, but something along these lines. Because I have tried to follow our manuals and I haven't found any information there related to choosing target board to MAZGCH anywhere. Maybe there is somewhere, but I haven't found it.

**Comment by rheyu-blox** [comment]
In the Readme of [this example](https://github.com/u-blox/XPLR-HPG-software/blob/main/XPLR-HPG-SW/examples/shortrange/03_hpg_wifi_mqtt_correction_certs/README.md).

**Comment by dbou-ublox** [comment]
Here you mean? 
![image](https://github.com/u-blox/XPLR-HPG-software/assets/74243444/cc1e3017-d41a-4ebe-855f-7e3704207da9)

**Comment by rheyu-blox** [comment]
exactly

**Comment by KValalaki** [comment]
Issue resolved and ticket is closed
